name: chilld_app
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  otp_text_field: ^1.1.3
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.2
  http: ^1.2.1
  loading_indicator: ^3.1.1
  webview_flutter: ^4.0.6
  loading_animation_widget: ^1.3.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1

    # App launcher icon configurations
flutter_icons:
  android: true
  ios: true
  image_path: "assets/1.png"
  adaptive_icon_background: "#FF0E4D94"
  # adaptive_icon_foreground: "assets/icons/logo_forground.png"
  min_sdk_android: 21 # android min sdk min:16, default 21


  # Splash Screen configurations
flutter_native_splash:
  color: "#114e93"
  image: "assets/splash.png"
  # color_dark: "#000000"
  # image_dark: "assets/icons/splash.png"
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center

  android_12:
    color: "#114e93"
    image: "assets/splash.png"
    # color_dark: "#000000"
    # image_dark: "assets/icons/splash.png"
    # android_gravity: center
    # ios_content_mode: center

  web: false
  intl: ^0.19.0
  shared_preferences: ^2.3.2



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/


